# Generated by Django 4.0.3 on 2022-04-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='ne_peut_vendre',
            field=models.BooleanField(default=True),
        ),
    ]
