# Generated by Django 4.0.3 on 2022-04-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_userregistrationmodel_ne_peut_vendre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='ne_peut_vendre',
            field=models.BooleanField(default=False, verbose_name='Je veux vendre'),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='numero_telephone',
            field=models.CharField(max_length=15, verbose_name='numero whatsapp'),
        ),
    ]
