# Generated by Django 4.0.3 on 2022-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
