# Generated by Django 4.0.3 on 2022-04-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='attente',
            field=models.BooleanField(default=False, verbose_name='Regler'),
        ),
    ]
