# Generated by Django 4.0.3 on 2022-04-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_commande_annuler_commande_regler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='attente',
            field=models.BooleanField(default=True, verbose_name='En attente'),
        ),
    ]
