# Generated by Django 4.0.3 on 2022-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_remove_order_ordered_orderitem_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
