# Generated by Django 4.0.3 on 2022-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frais_de_livraison',
            field=models.IntegerField(default=500, verbose_name='Frais De Livraison'),
        ),
        migrations.AddField(
            model_name='produit',
            name='mode_payement',
            field=models.CharField(default='Orange Money', max_length=100, verbose_name='Mode De Payement'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
